UPDATE scenarios SET
  alert_sequence = '[
    {"timestamp": "2021-05-07T04:45:00Z", "severity": "low", "source_system": "VPN Gateway", "rule_id": "VPN-AUTH-001", "description": "Single-factor VPN authentication from unusual IP 185.220.101.47 (Eastern Europe)", "raw_log": "May 07 04:45:12 vpn-gw01 auth: user jsmith login from 185.220.101.47"},
    {"timestamp": "2021-05-07T05:12:00Z", "severity": "medium", "source_system": "Active Directory", "rule_id": "AD-ENUM-003", "description": "Mass AD enumeration detected — BloodHound-style LDAP queries from internal host CORP-WS-047", "raw_log": "LDAP search from 10.10.5.47: (objectClass=*) base=DC=colonial,DC=com"},
    {"timestamp": "2021-05-07T05:58:00Z", "severity": "high", "source_system": "EDR (CrowdStrike)", "rule_id": "EDR-CRED-009", "description": "Mimikatz credential harvesting detected on CORP-WS-047. LSASS memory read by unsigned process.", "raw_log": "ProcessCreate: mimikatz.exe parent=cmd.exe user=SYSTEM"},
    {"timestamp": "2021-05-07T06:30:00Z", "severity": "critical", "source_system": "EDR (CrowdStrike)", "rule_id": "EDR-RANSOM-001", "description": "DarkSide ransomware binary dropped and executed on OT billing server BILL-SRV-03. Encryption initiated.", "raw_log": "FileCreate: .darkside extension mass write on BILL-SRV-03 by darkside.exe"},
    {"timestamp": "2021-05-07T06:45:00Z", "severity": "critical", "source_system": "SCADA Monitor", "rule_id": "OT-FLOW-002", "description": "Pipeline OT network lateral movement detected. Ransomware attempting to cross IT/OT boundary via shared VLAN.", "raw_log": "Unexpected SMB traffic from 10.10.5.47 to OT subnet 192.168.100.0/24"},
    {"timestamp": "2021-05-07T07:00:00Z", "severity": "critical", "source_system": "Operations Center", "rule_id": "OPS-SHUT-001", "description": "Executive decision made to proactively shut down 5,500-mile pipeline operations to prevent OT compromise.", "raw_log": "Manual shutdown initiated by ops-center. Affected: Colonial Pipeline main line."}
  ]'::jsonb,
  decision_tree = '[
    {"id": "gate-001", "trigger_timestamp": "2021-05-07T05:12:00Z", "context_summary": "AD enumeration is underway from an internal host. The attacker appears to have initial access via VPN. You have 10 minutes before they escalate privileges. What is your immediate containment action?", "options": [{"text": "Isolate CORP-WS-047 from the network immediately", "consequence_if_chosen": "Correct. Isolation stops lateral movement. Attacker loses foothold before credential harvest completes."}, {"text": "Monitor silently and gather more intelligence before acting", "consequence_if_chosen": "Wrong. 45 minutes of monitoring allowed Mimikatz to run and credentials were harvested, enabling full domain compromise."}, {"text": "Reset the VPN user password and notify the employee", "consequence_if_chosen": "Partially correct but insufficient. Attacker already has an internal foothold — VPN reset does not help."}], "correct_index": 0, "consequence_if_wrong": "Credential harvesting completed. Attacker now has domain admin credentials.", "rationale": "NIST IR guidance requires immediate containment once lateral movement is confirmed. Delay enables privilege escalation.", "nist_control_ref": "IR-4", "mitre_technique": "T1059"},
    {"id": "gate-002", "trigger_timestamp": "2021-05-07T06:30:00Z", "context_summary": "DarkSide ransomware is actively encrypting files on the billing server. The OT pipeline network is on a shared VLAN. Operations leadership is asking whether to shut down pipeline operations. What do you recommend?", "options": [{"text": "Recommend immediate proactive pipeline shutdown to prevent OT compromise", "consequence_if_chosen": "Correct. Proactive shutdown prevented ransomware from reaching OT systems. Fuel supply disruption was temporary and recoverable."}, {"text": "Keep pipeline running and focus IT containment only", "consequence_if_chosen": "Critical failure. Ransomware crossed the IT/OT boundary within 20 minutes, encrypting SCADA historian and forcing emergency shutdown under worse conditions."}, {"text": "Negotiate with DarkSide threat actors for decryption key", "consequence_if_chosen": "Risky. Colonial Pipeline paid $4.4M ransom. FBI later recovered $2.3M. Payment incentivises further attacks."}], "correct_index": 0, "consequence_if_wrong": "OT systems compromised. National fuel supply disruption extended to 11 days.", "rationale": "When ransomware is detected near OT/ICS boundaries, proactive isolation of critical infrastructure is the correct NIST response.", "nist_control_ref": "IR-4(1)", "mitre_technique": "T0816"}
  ]'::jsonb,
  mitre_techniques = ARRAY['T0822', 'T0859', 'T0890', 'T1059', 'T0816'],
  nist_controls = ARRAY['IR-4', 'IR-4(1)', 'AC-17', 'SI-3'],
  industry_vertical = 'energy',
  description = 'Simulation of the May 2021 DarkSide ransomware attack on Colonial Pipeline — the largest cyberattack on US critical infrastructure. Teams must navigate credential theft, lateral movement toward OT systems, and the critical decision of whether to shut down 5,500 miles of pipeline operations.'
WHERE id = '42e0791b-f84b-4d78-8bd0-524aa9a488b2';
